language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2
before_install:
  - gem update --system
install: "bundle install"
gemfile:
  - gemfiles/activemodel_3.0.gemfile
  - gemfiles/activemodel_3.1.gemfile
  - gemfiles/activemodel_3.2.gemfile
  - gemfiles/activemodel_4.0.gemfile
  - gemfiles/activemodel_4.1.gemfile
  - gemfiles/activemodel_4.2.gemfile
sudo: false
cache: bundler
